In [ ]:
print("Hello World")

Hello World

In [ ]:
import pandas as pd
pd.read_csv("/content/sample_data/mnist_test.csv")

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
Student={'Name':['Ram','Radha'],'Age':[25,30],'Marks':[99,89]}
print(Student)

{'Name': ['Ram', 'Radha'], 'Age': [25, 30], 'Marks': [99, 89]}

In [ ]:
Student_df=pd.DataFrame(Student)
print(Student_df)

    Name  Age  Marks
0    Ram   25     99
1  Radha   30     89

In [1]:
Samplelt=[10,20,40,25]
print(Samplelt)
fmList=pd.DataFrame(Samplelt)
print(fmList)

[10, 20, 40, 25]

NameError: name 'pd' is not defined

In [ ]:
fmList=pd.DataFrame(Samplelt,columns=['Numbers'])
print(fmList)

   Numbers
0       10
1       20
2       40
3       25